"""
Gemini File Search — Administrative Manual Query Tool (Multi-Doc)
================================================================
Hermes Agent Skill: Searches ALL uploaded administrative/normative documents
via the Google Gemini API. Documents are uploaded from OneDrive using
cargar_carpeta_onedrive.py and indexed in archivos_indexados.json.

Requires:
  - google-genai (pip install google-genai) OR google-generativeai (legacy)
  - GEMINI_API_KEY environment variable set on the Debian server
  - archivos_indexados.json generated by cargar_carpeta_onedrive.py
"""

import os
import json
import logging

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("gemini_admin_search")

# ── SDK Import (nuevo google-genai con fallback a legacy) ─────
_USE_NEW_SDK = False
try:
    from google import genai
    from google.genai import types
    _USE_NEW_SDK = True
except ImportError:
    try:
        import google.generativeai as genai
        _USE_NEW_SDK = False
    except ImportError:
        genai = None
        logger.warning("Ni google-genai ni google-generativeai están instalados.")


# ---------------------------------------------------------------------------
# Configuración
# ---------------------------------------------------------------------------
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY", "")
GEMINI_MODEL = "gemini-2.5-flash"

# Ruta al índice generado por cargar_carpeta_onedrive.py
SKILL_DIR = os.path.dirname(os.path.abspath(__file__))
INDEX_FILE = os.path.join(SKILL_DIR, "archivos_indexados.json")


# ---------------------------------------------------------------------------
# SDK Client initialization
# ---------------------------------------------------------------------------
_client = None

def _get_client():
    """Lazy-init del cliente para permitir configuración tardía del API key."""
    global _client
    if _client is not None:
        return _client
    
    api_key = GEMINI_API_KEY
    if not api_key:
        return None
    
    if _USE_NEW_SDK:
        _client = genai.Client(api_key=api_key)
    else:
        genai.configure(api_key=api_key)
        _client = genai  # En legacy, el módulo actúa como cliente
    
    return _client


# ---------------------------------------------------------------------------
# Helpers internos
# ---------------------------------------------------------------------------

def _cargar_indice() -> list:
    """Lee el índice de archivos sincronizados desde OneDrive."""
    if not os.path.exists(INDEX_FILE):
        return []
    try:
        with open(INDEX_FILE, "r", encoding="utf-8") as f:
            return json.load(f)
    except (json.JSONDecodeError, IOError) as e:
        logger.error(f"Error leyendo índice {INDEX_FILE}: {e}")
        return []


def _recuperar_documentos(indice: list) -> list:
    """
    Recupera las referencias de archivos desde Google AI Studio.
    Filtra los que ya no existan (eliminados manualmente, expirados, etc.)
    """
    client = _get_client()
    documentos = []
    
    for item in indice:
        id_gemini = item.get("id_gemini", "")
        nombre = item.get("nombre_local", "desconocido")
        try:
            if _USE_NEW_SDK:
                doc = client.files.get(name=id_gemini)
            else:
                doc = genai.get_file(id_gemini)
            documentos.append(doc)
            logger.debug(f"Documento cargado: {nombre} ({id_gemini})")
        except Exception as e:
            logger.warning(f"Documento '{nombre}' no disponible en Google: {e}")
    
    return documentos


# ---------------------------------------------------------------------------
# Funciones públicas (expuestas como herramientas al agente Hermes)
# ---------------------------------------------------------------------------

def consultar_manual_administrativo(pregunta: str) -> str:
    """
    Busca respuestas en los manuales administrativos y normativos de la farmacia.
    Los documentos provienen de la carpeta compartida de OneDrive sincronizada
    y subida a Google AI Studio.
    
    Úsala SOLO cuando el usuario o el agente necesite saber:
    - Reglas internas de la farmacia (devoluciones, garantías, cambios)
    - Procedimientos operativos (despacho, recepción, apertura, cierre)
    - Normativas legales y regulatorias del sector farmacéutico
    - Políticas de RRHH, horarios administrativos, turnos, permisos
    - Información administrativa que NO está en el inventario/base de datos
    
    NO usar para consultas de stock, precios o inventario 
    (para eso existe consultar_inventario).
    
    Args:
        pregunta (str): La consulta administrativa o normativa específica.
    
    Returns:
        str: La respuesta extraída del/los manual(es), o un mensaje de error.
    """
    if genai is None:
        return ("Error: Ni google-genai ni google-generativeai están instalados. "
                "Ejecuta: pip install google-genai")
    
    if not GEMINI_API_KEY:
        return ("Error: La variable de entorno GEMINI_API_KEY no está configurada. "
                "Configúrala en el servidor antes de usar esta herramienta.")
    
    try:
        client = _get_client()
        
        # 1. Leer el índice de archivos sincronizados
        indice = _cargar_indice()
        if not indice:
            return ("No se ha ejecutado la sincronización de manuales desde OneDrive. "
                    "Ejecuta 'cargar_carpeta_onedrive.py' primero para indexar los documentos.")
        
        # 2. Recuperar los documentos desde Google
        documentos = _recuperar_documentos(indice)
        if not documentos:
            return ("Los archivos indexados ya no están disponibles en Google AI Studio. "
                    "Re-ejecuta 'cargar_carpeta_onedrive.py --force' para re-subirlos.")
        
        # 3. Construir prompt
        nombres_docs = ", ".join([item["nombre_local"] for item in indice])
        
        prompt_instruccion = (
            "Eres un experto asistente de administración farmacéutica para Farmacia Americana. "
            "Tu ÚNICA fuente de información son los documentos adjuntos. "
            f"Documentos consultados: {nombres_docs}\n\n"
            "REGLAS ESTRICTAS:\n"
            "1. Responde de forma clara, concisa y basada EXCLUSIVAMENTE en el texto de los documentos.\n"
            "2. Si la información NO se encuentra en ningún documento, responde: "
            "'Esta información no se encuentra en los manuales administrativos disponibles.'\n"
            "3. Si encuentras información relevante en múltiples documentos, consolida la respuesta.\n"
            "4. Si hay contradicciones entre documentos, menciónalo explícitamente.\n"
            "5. Cita el nombre del documento de donde extraes la información.\n\n"
            f"Consulta: {pregunta}"
        )
        
        # 4. Llamar al modelo
        if _USE_NEW_SDK:
            # google-genai: usa client.models.generate_content()
            contenido = documentos + [prompt_instruccion]
            response = client.models.generate_content(
                model=GEMINI_MODEL,
                contents=contenido
            )
            resultado = response.text
        else:
            # google.generativeai (legacy)
            model = genai.GenerativeModel(model_name=f"models/{GEMINI_MODEL}")
            contenido = documentos + [prompt_instruccion]
            response = model.generate_content(contenido)
            resultado = response.text
        
        logger.info(f"Consulta administrativa procesada: '{pregunta[:60]}...' "
                    f"({len(documentos)} docs consultados)")
        return resultado
        
    except Exception as e:
        error_msg = f"Error al consultar los manuales administrativos: {str(e)}"
        logger.error(error_msg)
        return error_msg


def listar_manuales_disponibles() -> str:
    """
    Lista los manuales administrativos actualmente indexados y verifica
    su disponibilidad en Google AI Studio. Útil para diagnóstico.
    
    Returns:
        str: Lista de manuales y su estado (disponible/no disponible).
    """
    if genai is None:
        return "Error: google-genai/google-generativeai no instalado."
    
    if not GEMINI_API_KEY:
        return "Error: GEMINI_API_KEY no configurada."
    
    try:
        client = _get_client()
        
        indice = _cargar_indice()
        if not indice:
            return ("No hay manuales indexados. "
                    "Ejecuta 'cargar_carpeta_onedrive.py' para sincronizar desde OneDrive.")
        
        resultado = "=== Manuales Administrativos Indexados ===\n\n"
        disponibles = 0
        
        for item in indice:
            nombre = item.get("nombre_local", "?")
            id_gemini = item.get("id_gemini", "?")
            tamaño = item.get("tamaño_bytes", 0)
            fecha = item.get("fecha_subida", "?")
            
            try:
                if _USE_NEW_SDK:
                    doc = client.files.get(name=id_gemini)
                else:
                    doc = genai.get_file(id_gemini)
                
                estado = getattr(doc.state, 'name', str(doc.state)) if hasattr(doc, 'state') else 'OK'
                resultado += (f"✅ {nombre}\n"
                            f"   ID: {id_gemini}\n"
                            f"   Tamaño: {tamaño:,} bytes | Estado: {estado}\n"
                            f"   Sincronizado: {fecha}\n\n")
                disponibles += 1
            except Exception as e:
                resultado += (f"❌ {nombre}\n"
                            f"   ID: {id_gemini}\n"
                            f"   Error: {str(e)}\n\n")
        
        resultado += f"--- {disponibles}/{len(indice)} documentos disponibles ---"
        return resultado
        
    except Exception as e:
        return f"Error verificando manuales: {str(e)}"
