-- ============================================================
-- 013_sainsta_mdm_non_medicine.sql
-- SAINSTA 3-level MDM taxonomy (non-medicine).
-- Preserves Medicinas. Legacy non-medicine → LEGACY_NO_MEDICINA.
-- Phase-2 delete of legacy is a separate task.
-- REVIEW + BACKUP before production.
-- ============================================================
SET XACT_ABORT ON;
BEGIN TRANSACTION;

-- 0) Snapshot
IF OBJECT_ID(N'Procurement.SAINSTA_Backup_MDM', N'U') IS NULL
BEGIN
    SELECT * INTO Procurement.SAINSTA_Backup_MDM FROM dbo.SAINSTA;
END
IF OBJECT_ID(N'Procurement.SAPROD_CodInst_Backup_MDM', N'U') IS NULL
BEGIN
    SELECT CodProd, CodInst INTO Procurement.SAPROD_CodInst_Backup_MDM FROM dbo.SAPROD;
END

-- 1) LEGACY_NO_MEDICINA root (2999)
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 2999)
    UPDATE dbo.SAINSTA SET Descrip = N'LEGACY_NO_MEDICINA', InsPadre = 0 WHERE CodInst = 2999;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (2999, N'LEGACY_NO_MEDICINA', 0);

-- 2) Upsert MDM Dominio / Categoria / Subcategoria
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3000)
    UPDATE dbo.SAINSTA SET Descrip = N'COSMETICO_CUIDADO_PERSONAL', InsPadre = 0 WHERE CodInst = 3000;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3000, N'COSMETICO_CUIDADO_PERSONAL', 0);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3100)
    UPDATE dbo.SAINSTA SET Descrip = N'AFEITADO Y DEPILACION', InsPadre = 3000 WHERE CodInst = 3100;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3100, N'AFEITADO Y DEPILACION', 3000);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3200)
    UPDATE dbo.SAINSTA SET Descrip = N'PRODUCTOS PARA AFEITADO', InsPadre = 3100 WHERE CodInst = 3200;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3200, N'PRODUCTOS PARA AFEITADO', 3100);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3101)
    UPDATE dbo.SAINSTA SET Descrip = N'CUIDADO BUCAL', InsPadre = 3000 WHERE CodInst = 3101;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3101, N'CUIDADO BUCAL', 3000);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3201)
    UPDATE dbo.SAINSTA SET Descrip = N'CEPILLOS DENTALES', InsPadre = 3101 WHERE CodInst = 3201;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3201, N'CEPILLOS DENTALES', 3101);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3202)
    UPDATE dbo.SAINSTA SET Descrip = N'CREMAS DENTALES', InsPadre = 3101 WHERE CodInst = 3202;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3202, N'CREMAS DENTALES', 3101);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3203)
    UPDATE dbo.SAINSTA SET Descrip = N'ENJUAGUES BUCALES', InsPadre = 3101 WHERE CodInst = 3203;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3203, N'ENJUAGUES BUCALES', 3101);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3102)
    UPDATE dbo.SAINSTA SET Descrip = N'CUIDADO CAPILAR', InsPadre = 3000 WHERE CodInst = 3102;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3102, N'CUIDADO CAPILAR', 3000);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3204)
    UPDATE dbo.SAINSTA SET Descrip = N'CHAMPU Y ACONDICIONADOR', InsPadre = 3102 WHERE CodInst = 3204;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3204, N'CHAMPU Y ACONDICIONADOR', 3102);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3205)
    UPDATE dbo.SAINSTA SET Descrip = N'TINTES Y COLORACION', InsPadre = 3102 WHERE CodInst = 3205;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3205, N'TINTES Y COLORACION', 3102);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3206)
    UPDATE dbo.SAINSTA SET Descrip = N'TRATAMIENTOS CAPILARES', InsPadre = 3102 WHERE CodInst = 3206;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3206, N'TRATAMIENTOS CAPILARES', 3102);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3103)
    UPDATE dbo.SAINSTA SET Descrip = N'CUIDADO CORPORAL', InsPadre = 3000 WHERE CodInst = 3103;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3103, N'CUIDADO CORPORAL', 3000);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3207)
    UPDATE dbo.SAINSTA SET Descrip = N'CUIDADO DE MANOS Y PIES', InsPadre = 3103 WHERE CodInst = 3207;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3207, N'CUIDADO DE MANOS Y PIES', 3103);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3208)
    UPDATE dbo.SAINSTA SET Descrip = N'DESODORANTES Y ANTITRANSPIRANTES', InsPadre = 3103 WHERE CodInst = 3208;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3208, N'DESODORANTES Y ANTITRANSPIRANTES', 3103);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3209)
    UPDATE dbo.SAINSTA SET Descrip = N'HIDRATANTES CORPORALES', InsPadre = 3103 WHERE CodInst = 3209;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3209, N'HIDRATANTES CORPORALES', 3103);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3210)
    UPDATE dbo.SAINSTA SET Descrip = N'JABONES DE DUCHA Y BAÑO', InsPadre = 3103 WHERE CodInst = 3210;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3210, N'JABONES DE DUCHA Y BAÑO', 3103);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3211)
    UPDATE dbo.SAINSTA SET Descrip = N'PROTECTORES SOLARES CORPORALES', InsPadre = 3103 WHERE CodInst = 3211;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3211, N'PROTECTORES SOLARES CORPORALES', 3103);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3104)
    UPDATE dbo.SAINSTA SET Descrip = N'CUIDADO DEL BEBE', InsPadre = 3000 WHERE CodInst = 3104;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3104, N'CUIDADO DEL BEBE', 3000);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3212)
    UPDATE dbo.SAINSTA SET Descrip = N'HIGIENE Y CUIDADO DE LA PIEL', InsPadre = 3104 WHERE CodInst = 3212;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3212, N'HIGIENE Y CUIDADO DE LA PIEL', 3104);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3213)
    UPDATE dbo.SAINSTA SET Descrip = N'PAÑALES Y TOALLITAS HUMEDAS', InsPadre = 3104 WHERE CodInst = 3213;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3213, N'PAÑALES Y TOALLITAS HUMEDAS', 3104);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3105)
    UPDATE dbo.SAINSTA SET Descrip = N'CUIDADO FACIAL', InsPadre = 3000 WHERE CodInst = 3105;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3105, N'CUIDADO FACIAL', 3000);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3214)
    UPDATE dbo.SAINSTA SET Descrip = N'HIDRATANTES Y SERUMS', InsPadre = 3105 WHERE CodInst = 3214;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3214, N'HIDRATANTES Y SERUMS', 3105);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3215)
    UPDATE dbo.SAINSTA SET Descrip = N'LIMPIADORES Y DESMAQUILLANTES', InsPadre = 3105 WHERE CodInst = 3215;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3215, N'LIMPIADORES Y DESMAQUILLANTES', 3105);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3216)
    UPDATE dbo.SAINSTA SET Descrip = N'PROTECTORES SOLARES FACIALES', InsPadre = 3105 WHERE CodInst = 3216;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3216, N'PROTECTORES SOLARES FACIALES', 3105);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3217)
    UPDATE dbo.SAINSTA SET Descrip = N'TRATAMIENTOS ANTIACNE', InsPadre = 3105 WHERE CodInst = 3217;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3217, N'TRATAMIENTOS ANTIACNE', 3105);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3218)
    UPDATE dbo.SAINSTA SET Descrip = N'TRATAMIENTOS ANTIEDAD', InsPadre = 3105 WHERE CodInst = 3218;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3218, N'TRATAMIENTOS ANTIEDAD', 3105);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3106)
    UPDATE dbo.SAINSTA SET Descrip = N'HIGIENE INTIMA', InsPadre = 3000 WHERE CodInst = 3106;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3106, N'HIGIENE INTIMA', 3000);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3219)
    UPDATE dbo.SAINSTA SET Descrip = N'JABONES Y LIMPIADORES INTIMOS', InsPadre = 3106 WHERE CodInst = 3219;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3219, N'JABONES Y LIMPIADORES INTIMOS', 3106);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3220)
    UPDATE dbo.SAINSTA SET Descrip = N'PROTECCION FEMENINA', InsPadre = 3106 WHERE CodInst = 3220;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3220, N'PROTECCION FEMENINA', 3106);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3001)
    UPDATE dbo.SAINSTA SET Descrip = N'MATERIAL_MEDICO_INSUMO', InsPadre = 0 WHERE CodInst = 3001;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3001, N'MATERIAL_MEDICO_INSUMO', 0);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3107)
    UPDATE dbo.SAINSTA SET Descrip = N'CUIDADO DEL PACIENTE', InsPadre = 3001 WHERE CodInst = 3107;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3107, N'CUIDADO DEL PACIENTE', 3001);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3221)
    UPDATE dbo.SAINSTA SET Descrip = N'BOLSAS RECOLECTORAS', InsPadre = 3107 WHERE CodInst = 3221;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3221, N'BOLSAS RECOLECTORAS', 3107);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3222)
    UPDATE dbo.SAINSTA SET Descrip = N'PAÑALES PARA ADULTO', InsPadre = 3107 WHERE CodInst = 3222;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3222, N'PAÑALES PARA ADULTO', 3107);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3108)
    UPDATE dbo.SAINSTA SET Descrip = N'CUIDADO RESPIRATORIO', InsPadre = 3001 WHERE CodInst = 3108;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3108, N'CUIDADO RESPIRATORIO', 3001);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3223)
    UPDATE dbo.SAINSTA SET Descrip = N'NEBULIZADORES Y ACCESORIOS', InsPadre = 3108 WHERE CodInst = 3223;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3223, N'NEBULIZADORES Y ACCESORIOS', 3108);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3109)
    UPDATE dbo.SAINSTA SET Descrip = N'EQUIPOS DE DIAGNOSTICO', InsPadre = 3001 WHERE CodInst = 3109;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3109, N'EQUIPOS DE DIAGNOSTICO', 3001);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3224)
    UPDATE dbo.SAINSTA SET Descrip = N'GLUCOMETROS', InsPadre = 3109 WHERE CodInst = 3224;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3224, N'GLUCOMETROS', 3109);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3225)
    UPDATE dbo.SAINSTA SET Descrip = N'TENSIOMETROS', InsPadre = 3109 WHERE CodInst = 3225;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3225, N'TENSIOMETROS', 3109);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3226)
    UPDATE dbo.SAINSTA SET Descrip = N'TERMOMETROS', InsPadre = 3109 WHERE CodInst = 3226;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3226, N'TERMOMETROS', 3109);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3110)
    UPDATE dbo.SAINSTA SET Descrip = N'INSUMOS PARA DIABETES', InsPadre = 3001 WHERE CodInst = 3110;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3110, N'INSUMOS PARA DIABETES', 3001);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3227)
    UPDATE dbo.SAINSTA SET Descrip = N'LANCETAS', InsPadre = 3110 WHERE CodInst = 3227;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3227, N'LANCETAS', 3110);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3228)
    UPDATE dbo.SAINSTA SET Descrip = N'TIRAS REACTIVAS DE GLUCOSA', InsPadre = 3110 WHERE CodInst = 3228;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3228, N'TIRAS REACTIVAS DE GLUCOSA', 3110);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3111)
    UPDATE dbo.SAINSTA SET Descrip = N'INYECTOLOGIA', InsPadre = 3001 WHERE CodInst = 3111;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3111, N'INYECTOLOGIA', 3001);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3229)
    UPDATE dbo.SAINSTA SET Descrip = N'AGUJAS HIPODERMICAS', InsPadre = 3111 WHERE CodInst = 3229;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3229, N'AGUJAS HIPODERMICAS', 3111);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3230)
    UPDATE dbo.SAINSTA SET Descrip = N'CATETERES Y SONDAS', InsPadre = 3111 WHERE CodInst = 3230;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3230, N'CATETERES Y SONDAS', 3111);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3231)
    UPDATE dbo.SAINSTA SET Descrip = N'EQUIPOS DE INFUSION', InsPadre = 3111 WHERE CodInst = 3231;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3231, N'EQUIPOS DE INFUSION', 3111);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3232)
    UPDATE dbo.SAINSTA SET Descrip = N'JERINGAS CON AGUJA', InsPadre = 3111 WHERE CodInst = 3232;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3232, N'JERINGAS CON AGUJA', 3111);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3112)
    UPDATE dbo.SAINSTA SET Descrip = N'MATERIAL DE CURACION', InsPadre = 3001 WHERE CodInst = 3112;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3112, N'MATERIAL DE CURACION', 3001);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3233)
    UPDATE dbo.SAINSTA SET Descrip = N'ALGODON', InsPadre = 3112 WHERE CodInst = 3233;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3233, N'ALGODON', 3112);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3234)
    UPDATE dbo.SAINSTA SET Descrip = N'ANTISEPTICOS Y DESINFECTANTES', InsPadre = 3112 WHERE CodInst = 3234;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3234, N'ANTISEPTICOS Y DESINFECTANTES', 3112);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3235)
    UPDATE dbo.SAINSTA SET Descrip = N'GASAS Y APOSITOS', InsPadre = 3112 WHERE CodInst = 3235;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3235, N'GASAS Y APOSITOS', 3112);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3236)
    UPDATE dbo.SAINSTA SET Descrip = N'MASCARILLAS Y PROTECCION', InsPadre = 3112 WHERE CodInst = 3236;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3236, N'MASCARILLAS Y PROTECCION', 3112);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3237)
    UPDATE dbo.SAINSTA SET Descrip = N'ROPA QUIRURGICA DESCARTABLE', InsPadre = 3112 WHERE CodInst = 3237;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3237, N'ROPA QUIRURGICA DESCARTABLE', 3112);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3238)
    UPDATE dbo.SAINSTA SET Descrip = N'VENDAS Y CINTAS', InsPadre = 3112 WHERE CodInst = 3238;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3238, N'VENDAS Y CINTAS', 3112);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3113)
    UPDATE dbo.SAINSTA SET Descrip = N'ORTOPEDIA LIGERA', InsPadre = 3001 WHERE CodInst = 3113;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3113, N'ORTOPEDIA LIGERA', 3001);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3239)
    UPDATE dbo.SAINSTA SET Descrip = N'FAJAS Y SOPORTES LUMBARES', InsPadre = 3113 WHERE CodInst = 3239;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3239, N'FAJAS Y SOPORTES LUMBARES', 3113);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3240)
    UPDATE dbo.SAINSTA SET Descrip = N'MEDIAS DE COMPRESION', InsPadre = 3113 WHERE CodInst = 3240;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3240, N'MEDIAS DE COMPRESION', 3113);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3241)
    UPDATE dbo.SAINSTA SET Descrip = N'RODILLERAS Y TOBILLERAS', InsPadre = 3113 WHERE CodInst = 3241;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3241, N'RODILLERAS Y TOBILLERAS', 3113);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3114)
    UPDATE dbo.SAINSTA SET Descrip = N'PRIMEROS AUXILIOS', InsPadre = 3001 WHERE CodInst = 3114;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3114, N'PRIMEROS AUXILIOS', 3001);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3242)
    UPDATE dbo.SAINSTA SET Descrip = N'BOTIQUINES EQUIPADOS', InsPadre = 3114 WHERE CodInst = 3242;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3242, N'BOTIQUINES EQUIPADOS', 3114);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3243)
    UPDATE dbo.SAINSTA SET Descrip = N'GUANTES DESECHABLES', InsPadre = 3114 WHERE CodInst = 3243;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3243, N'GUANTES DESECHABLES', 3114);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3002)
    UPDATE dbo.SAINSTA SET Descrip = N'MISCELANEO', InsPadre = 0 WHERE CodInst = 3002;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3002, N'MISCELANEO', 0);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3115)
    UPDATE dbo.SAINSTA SET Descrip = N'ALIMENTOS', InsPadre = 3002 WHERE CodInst = 3115;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3115, N'ALIMENTOS', 3002);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3244)
    UPDATE dbo.SAINSTA SET Descrip = N'ALIMENTOS INFANTILES', InsPadre = 3115 WHERE CodInst = 3244;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3244, N'ALIMENTOS INFANTILES', 3115);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3245)
    UPDATE dbo.SAINSTA SET Descrip = N'BARRAS DE CEREAL Y ENERGETICAS', InsPadre = 3115 WHERE CodInst = 3245;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3245, N'BARRAS DE CEREAL Y ENERGETICAS', 3115);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3246)
    UPDATE dbo.SAINSTA SET Descrip = N'EDULCORANTES', InsPadre = 3115 WHERE CodInst = 3246;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3246, N'EDULCORANTES', 3115);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3247)
    UPDATE dbo.SAINSTA SET Descrip = N'FORMULAS INFANTILES', InsPadre = 3115 WHERE CodInst = 3247;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3247, N'FORMULAS INFANTILES', 3115);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3248)
    UPDATE dbo.SAINSTA SET Descrip = N'SNACKS SALUDABLES', InsPadre = 3115 WHERE CodInst = 3248;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3248, N'SNACKS SALUDABLES', 3115);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3116)
    UPDATE dbo.SAINSTA SET Descrip = N'BEBIDAS', InsPadre = 3002 WHERE CodInst = 3116;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3116, N'BEBIDAS', 3002);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3249)
    UPDATE dbo.SAINSTA SET Descrip = N'AGUA EMBOTELLADA', InsPadre = 3116 WHERE CodInst = 3249;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3249, N'AGUA EMBOTELLADA', 3116);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3250)
    UPDATE dbo.SAINSTA SET Descrip = N'BEBIDAS HIDRATANTES Y DEPORTIVAS', InsPadre = 3116 WHERE CodInst = 3250;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3250, N'BEBIDAS HIDRATANTES Y DEPORTIVAS', 3116);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3251)
    UPDATE dbo.SAINSTA SET Descrip = N'TES Y BEBIDAS FUNCIONALES', InsPadre = 3116 WHERE CodInst = 3251;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3251, N'TES Y BEBIDAS FUNCIONALES', 3116);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3117)
    UPDATE dbo.SAINSTA SET Descrip = N'BIENESTAR SEXUAL', InsPadre = 3002 WHERE CodInst = 3117;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3117, N'BIENESTAR SEXUAL', 3002);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3252)
    UPDATE dbo.SAINSTA SET Descrip = N'LUBRICANTES', InsPadre = 3117 WHERE CodInst = 3252;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3252, N'LUBRICANTES', 3117);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3253)
    UPDATE dbo.SAINSTA SET Descrip = N'PRESERVATIVOS', InsPadre = 3117 WHERE CodInst = 3253;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3253, N'PRESERVATIVOS', 3117);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3254)
    UPDATE dbo.SAINSTA SET Descrip = N'PRUEBAS DE EMBARAZO Y OVULACION', InsPadre = 3117 WHERE CodInst = 3254;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3254, N'PRUEBAS DE EMBARAZO Y OVULACION', 3117);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3118)
    UPDATE dbo.SAINSTA SET Descrip = N'CUIDADO DEL HOGAR', InsPadre = 3002 WHERE CodInst = 3118;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3118, N'CUIDADO DEL HOGAR', 3002);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3255)
    UPDATE dbo.SAINSTA SET Descrip = N'REPELENTES DE INSECTOS', InsPadre = 3118 WHERE CodInst = 3255;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3255, N'REPELENTES DE INSECTOS', 3118);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3119)
    UPDATE dbo.SAINSTA SET Descrip = N'MASCOTAS', InsPadre = 3002 WHERE CodInst = 3119;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3119, N'MASCOTAS', 3002);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3256)
    UPDATE dbo.SAINSTA SET Descrip = N'ANTIPULGAS Y GARRAPATAS', InsPadre = 3119 WHERE CodInst = 3256;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3256, N'ANTIPULGAS Y GARRAPATAS', 3119);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3120)
    UPDATE dbo.SAINSTA SET Descrip = N'OPTICA', InsPadre = 3002 WHERE CodInst = 3120;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3120, N'OPTICA', 3002);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3257)
    UPDATE dbo.SAINSTA SET Descrip = N'GOTAS LUBRICANTES OCULARES', InsPadre = 3120 WHERE CodInst = 3257;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3257, N'GOTAS LUBRICANTES OCULARES', 3120);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3258)
    UPDATE dbo.SAINSTA SET Descrip = N'LENTES DE LECTURA', InsPadre = 3120 WHERE CodInst = 3258;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3258, N'LENTES DE LECTURA', 3120);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3259)
    UPDATE dbo.SAINSTA SET Descrip = N'SOLUCIONES PARA LENTES DE CONTACTO', InsPadre = 3120 WHERE CodInst = 3259;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3259, N'SOLUCIONES PARA LENTES DE CONTACTO', 3120);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3121)
    UPDATE dbo.SAINSTA SET Descrip = N'VARIOS', InsPadre = 3002 WHERE CodInst = 3121;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3121, N'VARIOS', 3002);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3260)
    UPDATE dbo.SAINSTA SET Descrip = N'BATERIAS', InsPadre = 3121 WHERE CodInst = 3260;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3260, N'BATERIAS', 3121);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3261)
    UPDATE dbo.SAINSTA SET Descrip = N'DULCES Y GOMAS DE MASCAR', InsPadre = 3121 WHERE CodInst = 3261;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3261, N'DULCES Y GOMAS DE MASCAR', 3121);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3003)
    UPDATE dbo.SAINSTA SET Descrip = N'PRODUCTO_NATURAL_HOMEOPATICO', InsPadre = 0 WHERE CodInst = 3003;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3003, N'PRODUCTO_NATURAL_HOMEOPATICO', 0);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3122)
    UPDATE dbo.SAINSTA SET Descrip = N'AROMATERAPIA', InsPadre = 3003 WHERE CodInst = 3122;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3122, N'AROMATERAPIA', 3003);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3262)
    UPDATE dbo.SAINSTA SET Descrip = N'ACEITES ESENCIALES', InsPadre = 3122 WHERE CodInst = 3262;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3262, N'ACEITES ESENCIALES', 3122);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3123)
    UPDATE dbo.SAINSTA SET Descrip = N'FITOTERAPIA', InsPadre = 3003 WHERE CodInst = 3123;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3123, N'FITOTERAPIA', 3003);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3263)
    UPDATE dbo.SAINSTA SET Descrip = N'CIRCULATORIOS', InsPadre = 3123 WHERE CodInst = 3263;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3263, N'CIRCULATORIOS', 3123);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3264)
    UPDATE dbo.SAINSTA SET Descrip = N'CONTROL DE PESO', InsPadre = 3123 WHERE CodInst = 3264;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3264, N'CONTROL DE PESO', 3123);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3265)
    UPDATE dbo.SAINSTA SET Descrip = N'DEFENSAS Y SISTEMA INMUNE', InsPadre = 3123 WHERE CodInst = 3265;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3265, N'DEFENSAS Y SISTEMA INMUNE', 3123);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3266)
    UPDATE dbo.SAINSTA SET Descrip = N'DIGESTIVOS', InsPadre = 3123 WHERE CodInst = 3266;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3266, N'DIGESTIVOS', 3123);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3267)
    UPDATE dbo.SAINSTA SET Descrip = N'ESTIMULANTES Y ENERGIZANTES', InsPadre = 3123 WHERE CodInst = 3267;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3267, N'ESTIMULANTES Y ENERGIZANTES', 3123);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3268)
    UPDATE dbo.SAINSTA SET Descrip = N'MEMORIA Y CONCENTRACION', InsPadre = 3123 WHERE CodInst = 3268;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3268, N'MEMORIA Y CONCENTRACION', 3123);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3269)
    UPDATE dbo.SAINSTA SET Descrip = N'RELAJANTES Y SEDANTES', InsPadre = 3123 WHERE CodInst = 3269;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3269, N'RELAJANTES Y SEDANTES', 3123);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3124)
    UPDATE dbo.SAINSTA SET Descrip = N'FLORES DE BACH', InsPadre = 3003 WHERE CodInst = 3124;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3124, N'FLORES DE BACH', 3003);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3270)
    UPDATE dbo.SAINSTA SET Descrip = N'FORMULAS FLORALES', InsPadre = 3124 WHERE CodInst = 3270;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3270, N'FORMULAS FLORALES', 3124);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3125)
    UPDATE dbo.SAINSTA SET Descrip = N'HOMEOPATIA', InsPadre = 3003 WHERE CodInst = 3125;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3125, N'HOMEOPATIA', 3003);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3271)
    UPDATE dbo.SAINSTA SET Descrip = N'GOTAS Y SOLUCIONES', InsPadre = 3125 WHERE CodInst = 3271;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3271, N'GOTAS Y SOLUCIONES', 3125);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3272)
    UPDATE dbo.SAINSTA SET Descrip = N'GRANULOS Y GLOBULOS', InsPadre = 3125 WHERE CodInst = 3272;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3272, N'GRANULOS Y GLOBULOS', 3125);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3126)
    UPDATE dbo.SAINSTA SET Descrip = N'INFUSIONES HERBALES', InsPadre = 3003 WHERE CodInst = 3126;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3126, N'INFUSIONES HERBALES', 3003);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3273)
    UPDATE dbo.SAINSTA SET Descrip = N'INFUSIONES DIGESTIVAS', InsPadre = 3126 WHERE CodInst = 3273;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3273, N'INFUSIONES DIGESTIVAS', 3126);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3274)
    UPDATE dbo.SAINSTA SET Descrip = N'INFUSIONES RELAJANTES', InsPadre = 3126 WHERE CodInst = 3274;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3274, N'INFUSIONES RELAJANTES', 3126);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3127)
    UPDATE dbo.SAINSTA SET Descrip = N'SUPLEMENTOS APICOLAS', InsPadre = 3003 WHERE CodInst = 3127;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3127, N'SUPLEMENTOS APICOLAS', 3003);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3275)
    UPDATE dbo.SAINSTA SET Descrip = N'JALEA REAL', InsPadre = 3127 WHERE CodInst = 3275;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3275, N'JALEA REAL', 3127);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3276)
    UPDATE dbo.SAINSTA SET Descrip = N'PROPOLEO', InsPadre = 3127 WHERE CodInst = 3276;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3276, N'PROPOLEO', 3127);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3128)
    UPDATE dbo.SAINSTA SET Descrip = N'SUPLEMENTOS HERBALES', InsPadre = 3003 WHERE CodInst = 3128;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3128, N'SUPLEMENTOS HERBALES', 3003);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3277)
    UPDATE dbo.SAINSTA SET Descrip = N'CURCUMA', InsPadre = 3128 WHERE CodInst = 3277;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3277, N'CURCUMA', 3128);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3278)
    UPDATE dbo.SAINSTA SET Descrip = N'ESPIRULINA', InsPadre = 3128 WHERE CodInst = 3278;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3278, N'ESPIRULINA', 3128);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3004)
    UPDATE dbo.SAINSTA SET Descrip = N'SUPLEMENTO_VITAMINICO', InsPadre = 0 WHERE CodInst = 3004;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3004, N'SUPLEMENTO_VITAMINICO', 0);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3129)
    UPDATE dbo.SAINSTA SET Descrip = N'ACIDOS GRASOS', InsPadre = 3004 WHERE CodInst = 3129;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3129, N'ACIDOS GRASOS', 3004);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3279)
    UPDATE dbo.SAINSTA SET Descrip = N'OMEGA 3-6-9', InsPadre = 3129 WHERE CodInst = 3279;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3279, N'OMEGA 3-6-9', 3129);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3130)
    UPDATE dbo.SAINSTA SET Descrip = N'ANTIOXIDANTES', InsPadre = 3004 WHERE CodInst = 3130;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3130, N'ANTIOXIDANTES', 3004);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3280)
    UPDATE dbo.SAINSTA SET Descrip = N'COENZIMA Q10', InsPadre = 3130 WHERE CodInst = 3280;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3280, N'COENZIMA Q10', 3130);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3131)
    UPDATE dbo.SAINSTA SET Descrip = N'MINERALES', InsPadre = 3004 WHERE CodInst = 3131;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3131, N'MINERALES', 3004);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3281)
    UPDATE dbo.SAINSTA SET Descrip = N'CALCIO', InsPadre = 3131 WHERE CodInst = 3281;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3281, N'CALCIO', 3131);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3282)
    UPDATE dbo.SAINSTA SET Descrip = N'HIERRO', InsPadre = 3131 WHERE CodInst = 3282;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3282, N'HIERRO', 3131);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3283)
    UPDATE dbo.SAINSTA SET Descrip = N'MAGNESIO', InsPadre = 3131 WHERE CodInst = 3283;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3283, N'MAGNESIO', 3131);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3284)
    UPDATE dbo.SAINSTA SET Descrip = N'ZINC', InsPadre = 3131 WHERE CodInst = 3284;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3284, N'ZINC', 3131);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3132)
    UPDATE dbo.SAINSTA SET Descrip = N'MULTIVITAMINICOS', InsPadre = 3004 WHERE CodInst = 3132;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3132, N'MULTIVITAMINICOS', 3004);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3285)
    UPDATE dbo.SAINSTA SET Descrip = N'MULTIVITAMINICOS ADULTO', InsPadre = 3132 WHERE CodInst = 3285;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3285, N'MULTIVITAMINICOS ADULTO', 3132);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3286)
    UPDATE dbo.SAINSTA SET Descrip = N'MULTIVITAMINICOS HOMBRE', InsPadre = 3132 WHERE CodInst = 3286;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3286, N'MULTIVITAMINICOS HOMBRE', 3132);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3287)
    UPDATE dbo.SAINSTA SET Descrip = N'MULTIVITAMINICOS INFANTIL', InsPadre = 3132 WHERE CodInst = 3287;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3287, N'MULTIVITAMINICOS INFANTIL', 3132);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3288)
    UPDATE dbo.SAINSTA SET Descrip = N'MULTIVITAMINICOS MUJER', InsPadre = 3132 WHERE CodInst = 3288;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3288, N'MULTIVITAMINICOS MUJER', 3132);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3289)
    UPDATE dbo.SAINSTA SET Descrip = N'PRENATALES', InsPadre = 3132 WHERE CodInst = 3289;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3289, N'PRENATALES', 3132);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3133)
    UPDATE dbo.SAINSTA SET Descrip = N'PROBIOTICOS', InsPadre = 3004 WHERE CodInst = 3133;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3133, N'PROBIOTICOS', 3004);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3290)
    UPDATE dbo.SAINSTA SET Descrip = N'PROBIOTICOS ADULTO', InsPadre = 3133 WHERE CodInst = 3290;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3290, N'PROBIOTICOS ADULTO', 3133);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3291)
    UPDATE dbo.SAINSTA SET Descrip = N'PROBIOTICOS INFANTIL', InsPadre = 3133 WHERE CodInst = 3291;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3291, N'PROBIOTICOS INFANTIL', 3133);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3134)
    UPDATE dbo.SAINSTA SET Descrip = N'PROTEINAS Y AMINOACIDOS', InsPadre = 3004 WHERE CodInst = 3134;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3134, N'PROTEINAS Y AMINOACIDOS', 3004);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3292)
    UPDATE dbo.SAINSTA SET Descrip = N'COLAGENO', InsPadre = 3134 WHERE CodInst = 3292;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3292, N'COLAGENO', 3134);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3293)
    UPDATE dbo.SAINSTA SET Descrip = N'PROTEINA EN POLVO', InsPadre = 3134 WHERE CodInst = 3293;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3293, N'PROTEINA EN POLVO', 3134);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3135)
    UPDATE dbo.SAINSTA SET Descrip = N'VITAMINAS', InsPadre = 3004 WHERE CodInst = 3135;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3135, N'VITAMINAS', 3004);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3294)
    UPDATE dbo.SAINSTA SET Descrip = N'COMPLEJO B', InsPadre = 3135 WHERE CodInst = 3294;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3294, N'COMPLEJO B', 3135);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3295)
    UPDATE dbo.SAINSTA SET Descrip = N'VITAMINA C', InsPadre = 3135 WHERE CodInst = 3295;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3295, N'VITAMINA C', 3135);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3296)
    UPDATE dbo.SAINSTA SET Descrip = N'VITAMINA D', InsPadre = 3135 WHERE CodInst = 3296;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3296, N'VITAMINA D', 3135);
IF EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 3297)
    UPDATE dbo.SAINSTA SET Descrip = N'VITAMINA E', InsPadre = 3135 WHERE CodInst = 3297;
ELSE
    INSERT INTO dbo.SAINSTA (CodInst, Descrip, InsPadre) VALUES (3297, N'VITAMINA E', 3135);

-- 3) Medicinas subtree (preserve)
;WITH MedicinasTree AS (
    SELECT CodInst FROM dbo.SAINSTA
    WHERE Descrip = N'Medicinas' AND ISNULL(InsPadre, 0) = 0
    UNION ALL
    SELECT c.CodInst
    FROM dbo.SAINSTA c
    INNER JOIN MedicinasTree p ON c.InsPadre = p.CodInst
)
SELECT CodInst INTO #MedicinasPreserve FROM MedicinasTree;

-- 4) Reparent non-medicine / non-MDM / non-Anulados under LEGACY
UPDATE i
SET InsPadre = 2999
FROM dbo.SAINSTA AS i
WHERE i.CodInst <> 2999
  AND i.CodInst <> 27
  AND ISNULL(i.InsPadre, 0) <> 27
  AND ISNULL(i.InsPadre, 0) <> 2999
  AND i.CodInst NOT BETWEEN 3000 AND 3999
  AND i.CodInst NOT IN (SELECT CodInst FROM #MedicinasPreserve)
  AND i.Descrip <> N'Anulados o Eliminadas';

-- 5) Optional SAPROD remap when MDM columns exist (prefer subcategoria)
IF COL_LENGTH('Procurement.por_aprobacion_equivalencias', 'dominio') IS NOT NULL
 AND COL_LENGTH('Procurement.por_aprobacion_equivalencias', 'categoria') IS NOT NULL
 AND COL_LENGTH('Procurement.por_aprobacion_equivalencias', 'subcategoria') IS NOT NULL
BEGIN
    ;WITH MapSub AS (
        SELECT e.codbarras, s.CodInst
        FROM Procurement.por_aprobacion_equivalencias e
        INNER JOIN dbo.SAINSTA s ON s.Descrip = e.subcategoria
        INNER JOIN dbo.SAINSTA c ON c.CodInst = s.InsPadre AND c.Descrip = e.categoria
        INNER JOIN dbo.SAINSTA d ON d.CodInst = c.InsPadre AND d.Descrip = e.dominio
        WHERE e.dominio IS NOT NULL AND e.categoria IS NOT NULL AND e.subcategoria IS NOT NULL
          AND e.dominio <> N'MEDICAMENTO_ALOPATICO'
    )
    UPDATE p SET CodInst = m.CodInst
    FROM dbo.SAPROD p
    INNER JOIN MapSub m ON p.CodProd = m.codbarras
    WHERE p.CodInst NOT IN (SELECT CodInst FROM #MedicinasPreserve);

    ;WITH MapCat AS (
        SELECT e.codbarras, c.CodInst
        FROM Procurement.por_aprobacion_equivalencias e
        INNER JOIN dbo.SAINSTA c ON c.Descrip = e.categoria
        INNER JOIN dbo.SAINSTA d ON d.CodInst = c.InsPadre AND d.Descrip = e.dominio
        WHERE e.dominio IS NOT NULL AND e.categoria IS NOT NULL
          AND (e.subcategoria IS NULL OR LTRIM(RTRIM(e.subcategoria)) = N'')
          AND e.dominio <> N'MEDICAMENTO_ALOPATICO'
    )
    UPDATE p SET CodInst = m.CodInst
    FROM dbo.SAPROD p
    INNER JOIN MapCat m ON p.CodProd = m.codbarras
    WHERE p.CodInst NOT IN (SELECT CodInst FROM #MedicinasPreserve);
END

-- 6) Sanity
IF NOT EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE Descrip = N'Medicinas' AND ISNULL(InsPadre, 0) = 0)
BEGIN
    RAISERROR(N'Medicinas root missing after migration', 16, 1);
    ROLLBACK TRANSACTION;
    RETURN;
END
IF NOT EXISTS (SELECT 1 FROM dbo.SAINSTA WHERE CodInst = 2999)
BEGIN
    RAISERROR(N'LEGACY_NO_MEDICINA missing after migration', 16, 1);
    ROLLBACK TRANSACTION;
    RETURN;
END

COMMIT TRANSACTION;
GO

-- Taxonomy version: 2
-- Insertable nodes: 140
